-- Zapytanie 1
-- Wypisz imiona i nazwiska osób, które maj¹ drug¹ klase trenersk¹.
SELECT IMIE, NAZWISKO
FROM OSOBA
INNER JOIN TRENER
ON Osoba.ID_OSOBA = Trener.ID_TRENER
INNER JOIN Klasa_Trenerska
ON Trener.KLASA_TRENERSKA_ID_KLASA = Klasa_Trenerska.ID_KLASA
WHERE Klasa_Trenerska.KLASA = 2;

-- Zapytanie 2
-- Wypisz imiê i nazwisko osoby, która sêdziow³a w meczu dru¿yny 4.
SELECT IMIE, NAZWISKO
FROM OSOBA
INNER JOIN SEDZIA
ON OSOBA.ID_OSOBA = SEDZIA.ID_SEDZIA
INNER JOIN MECZ
ON SEDZIA.ID_SEDZIA = MECZ.SEDZIA_ID_SEDZIA
WHERE MECZ.DRUZYNA_ID_DRUZYNA = 4 OR MECZ.DRUZYNA_2_ID_DRUZYNA = 4;

-- Zapytanie 3
-- Wypisz imiona i nazwiska osób, które pracuj¹ w urzêdzie przy ulicy ¯eromskiego.
SELECT IMIE, NAZWISKO
FROM OSOBA
INNER JOIN URZAD
ON OSOBA.URZAD_ID_URZAD = URZAD.ID_URZAD
INNER JOIN ADRES
ON URZAD.ADRES_ID_ADRES = ADRES.ID_ADRES
WHERE ADRES.ULICA = '¯eromskiego';

-- Zapytanie 4
-- Wypisz informacje nt. hali w której odby³ siê mecz 25.10.2017r.
SELECT HALA.NAZWA, ADRES.ULICA, ADRES.NR_DZIALKI, ADRES.KOD_POCZTOWY, MIASTO.MIASTO
FROM MIASTO
INNER JOIN ADRES
ON MIASTO.ID_MIASTO = ADRES.MIASTO_ID_MIASTO
INNER JOIN HALA
ON ADRES.ID_ADRES = HALA.ADRES_ID_ADRES
INNER JOIN MECZ
ON HALA.ID_HALA = MECZ.HALA_ID_HALA
WHERE MECZ.TERMIN > '2017/10/24' and MECZ.TERMIN < '2017/10/26';

-- Zapytanie 5
-- Wypisz iloœæ punktów zdobytych w poszczególnych meczach przez zawodników graj¹cych w obu dru¿ynach. Wyniki uszereguj zgodnie z malej¹c¹ liczb¹ punktów.
SELECT MECZ_ID_MECZ, SUM(ILOSC_ZDOBYTYCH_PUNKTOW)
FROM STATYSTYKA
GROUP BY MECZ_ID_MECZ
ORDER BY SUM(ILOSC_ZDOBYTYCH_PUNKTOW) DESC;

-- Zapytanie 6
-- Wypisz ³¹czn¹ iloœæ punktów zdobytych przez zawodników z poszczególnych urzêdów.
SELECT URZAD.NAZWA, SUM(STATYSTYKA.ILOSC_ZDOBYTYCH_PUNKTOW)  
FROM URZAD
INNER JOIN OSOBA
ON URZAD.ID_URZAD = OSOBA.URZAD_ID_URZAD
INNER JOIN ZAWODNIK
ON OSOBA.ID_OSOBA = ZAWODNIK.ID_ZAWODNIK
INNER JOIN ZAWODNIK_W_DRUZYNIE
ON ZAWODNIK.ID_ZAWODNIK = ZAWODNIK_W_DRUZYNIE.ZAWODNIK_ID_ZAWODNIK
INNER JOIN STATYSTYKA
ON ZAWODNIK_W_DRUZYNIE.STATYSTYKA_ID_STATYSTYKA = STATYSTYKA.ID_STATYSTYKA
GROUP BY OSOBA.URZAD_ID_URZAD, URZAD.NAZWA;

-- Zapytanie 7
-- Zawodnika o numerze Id 5 ma koszulkê z numerem 10. Zmieñ ten numer na 12. 
UPDATE ZAWODNIK 
SET NR_NA_KOSZULCE = 12
WHERE ID_ZAWODNIK = 5;

-- Zapytanie 8
-- Z tabeli KLASA_TRENERSKA usuñ wszystkie rekordy dla których wartoœæ pola KLASA jest NULL. 
DELETE FROM KLASA_TRENERSKA
WHERE KLASA IS NULL;

-- Zapytanie 9
-- ZnajdŸ zawodników którzy zdobyli wiêcej ni¿ 65 punktów.
SELECT ID_OSOBA, IMIE, NAZWISKO, SUMA
FROM (SELECT ID_OSOBA, IMIE, NAZWISKO, URZAD.NAZWA, SUM(STATYSTYKA.ILOSC_ZDOBYTYCH_PUNKTOW) SUMA
        FROM URZAD 
        INNER JOIN OSOBA
        ON URZAD.ID_URZAD = OSOBA.URZAD_ID_URZAD
        INNER JOIN ZAWODNIK
        ON OSOBA.ID_OSOBA = ZAWODNIK.ID_ZAWODNIK
        INNER JOIN ZAWODNIK_W_DRUZYNIE
        ON ZAWODNIK.ID_ZAWODNIK = ZAWODNIK_W_DRUZYNIE.ZAWODNIK_ID_ZAWODNIK
        INNER JOIN STATYSTYKA
        ON ZAWODNIK_W_DRUZYNIE.STATYSTYKA_ID_STATYSTYKA = STATYSTYKA.ID_STATYSTYKA
        GROUP BY ID_OSOBA, IMIE, NAZWISKO, URZAD.NAZWA
        ORDER BY SUMA) 
WHERE SUMA > 65;
        
-- Zadanie 10
-- ZnajdŸ zawodników, z poszczególnych urzêdów który zdobyli najwiêcej punktów w jednym meczu, w swoim urzêdzie.
SELECT IMIE, NAZWISKO, URZ.NAZWA, STATYSTYKA.ILOSC_ZDOBYTYCH_PUNKTOW
FROM URZAD URZ 
INNER JOIN OSOBA
ON URZ.ID_URZAD = OSOBA.URZAD_ID_URZAD
INNER JOIN ZAWODNIK
ON OSOBA.ID_OSOBA = ZAWODNIK.ID_ZAWODNIK
INNER JOIN ZAWODNIK_W_DRUZYNIE
ON ZAWODNIK.ID_ZAWODNIK = ZAWODNIK_W_DRUZYNIE.ZAWODNIK_ID_ZAWODNIK
INNER JOIN STATYSTYKA        
ON ZAWODNIK_W_DRUZYNIE.STATYSTYKA_ID_STATYSTYKA = STATYSTYKA.ID_STATYSTYKA
WHERE STATYSTYKA.ILOSC_ZDOBYTYCH_PUNKTOW = (SELECT MAX(STATYSTYKA.ILOSC_ZDOBYTYCH_PUNKTOW)
                                                    FROM URZAD  
                                                    INNER JOIN OSOBA
                                                    ON URZAD.ID_URZAD = OSOBA.URZAD_ID_URZAD
                                                    INNER JOIN ZAWODNIK
                                                    ON OSOBA.ID_OSOBA = ZAWODNIK.ID_ZAWODNIK
                                                    INNER JOIN ZAWODNIK_W_DRUZYNIE
                                                    ON ZAWODNIK.ID_ZAWODNIK = ZAWODNIK_W_DRUZYNIE.ZAWODNIK_ID_ZAWODNIK
                                                    INNER JOIN STATYSTYKA
                                                    ON ZAWODNIK_W_DRUZYNIE.STATYSTYKA_ID_STATYSTYKA = STATYSTYKA.ID_STATYSTYKA
                                                    WHERE URZAD.NAZWA = URZ.NAZWA) 
GROUP BY IMIE, NAZWISKO, URZ.NAZWA, STATYSTYKA.ILOSC_ZDOBYTYCH_PUNKTOW;



